### PR TITLE
Pushback misbehaving fix

### LINKED ISSUE #99: Pushback misbehaving
**Describe the bug**
The player randomly moves when no inputs are given to the game.
This is caused by the `Pushback` Locomotion on the player.
It is extremely obvious when the player is in an enclosed space like the elevator.

**To Reproduce**
1. Pull any branch after v0.5.0
2. Play `city-01` scene without a VR headset or similar connected 
3. Wait for Player to randomly move 
4. Stop the game
5. find `Player/Locomotion/Pushback` in the hierarchy and disable it
6. Play `city-01` again
7. Notice Player doesn't randomly move

**Expected behavior**
Player should only be moved by the `Pushback` Locomotion when they are attempting to clip OOB

**Screen Recording**
https://github.com/user-attachments/assets/70c8f199-6a40-4b5c-830e-0d8a193f0a46

### PR DESCRIPTION
**Pull request by otherotherjosh**
# Issue
> **Describe the bug**
> The player randomly moves when no inputs are given to the game.
> This is caused by the `Pushback` Locomotion on the player.
> It is extremely obvious when the player is in an enclosed space like the elevator.

Closes #99

# Changes
- Set NPC vision cone layer to "NPC" (cones were causing pushback to push back)
- Removed some unnecessary code from pushback script

# File locations
**XRPushbackProvider:** *OurFiles/Scripts/*
**Vision cone:** *OurFiles/Prefabs/Resources/NPC.prefab*

### CODE REVIEW

File: Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs [hunk 1]
```diff
@@ -55,7 +53,7 @@ private List<RaycastHit> DetectCollision(Transform origin, float distance, Layer
         List<RaycastHit> newDetectedHits = new();
 
         List<Vector3> directions = new() { origin.forward, origin.right, -origin.right };
-        
+
```
Comment (Christian-Irvine) [inline Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs:56]: I really like the changes here.

**Review by Christian-Irvine — APPROVED** [review]
As a gamer this works. As a non gamer, this also works. I'm so glad this bug is fixed because it was really annoying. Happy to approve the branch the code looks good.

**Review by AmberSolstice — APPROVED** [review]
The fix looks good. Updating the NPC vision cone to its own layer makes sense and should prevent recursive pushback issues. The cleanup in XRPushbackProvider also simplifies the update loop and keeps motion handling clearer. I don’t see any problems with these changes. Nice work.
