### PR TITLE
Fade To black bug fix 

### LINKED ISSUE #103: Fade to black dupe material
**Describe the bug**
Closing the game while fade to black breaks the material's values

**To Reproduce**
1. Load Main Menu
2. Click "Play"
3. Close the game while the screen is fading to black
4. Look at material transparency value, it should be 0 while game is not running

**Expected behavior**
If you close the game the fade to black works on next game launch 

**Screenshots and/or Screen Recordings**
N/A

**Additional context**
Create a duplicate material on game start instead of editing the original material's values

### PR DESCRIPTION
**Pull request by MikeBike2**
## Overview
Fixed Issue by creating an instance of the fade material and also preserved the original state of the RGB to be called afterwards as well as a few other safe guards to avoid this error.
I wanted to do more testing however my game broke due to an unrelated prefab error at the time. (not sure why)

### Changed
Assets/OurFiles/Scripts/SceneLoading/SceneLoader.cs
### Fixed
Fade to black bug which was caused by exiting the game early and was not being reset on game launch 
### Removed
Modified some existing code related to applying this fade out.

## How to test changes
1. Pull `MikeBike2-8-fade-to-black-dupe-material` branch
2. Open Mikes Scenes(fadetoblackscene)
3. Quit game as fade to black is happening(modify speed values to do this easier)
image

4. relaunch game and should have no black screen anymore

## Issue number and link
Closes #103

### CODE REVIEW

**Review by Christian-Irvine — DISMISSED** [review]
Nice work, I found the `Mathf.Approximately` very nice I didn't know it existed. However there is an issue where you changed `MainMenuScene`, `Tutorial`, and `city-01` scenes. I don't think you needed to do this and they should be duplicated scenes anyway to avoid merge conflicts. I would like these changes to be made before its ready for merge.

File: Assets/OurFiles/Scripts/SceneLoading/SceneLoader.cs [hunk 1]
```diff
@@ -14,6 +14,22 @@ public class SceneLoader : Singleton<SceneLoader>
...
+        base.Awake();
+        // create a material instance so original asset is not modified
+        fadeMatInstance = new Material(blackFadeMaterial);
+
+        // reset alpha at start so fade is transparent on launch
+        Color c = fadeMatInstance.color;
+        c.a = 0;
+        fadeMatInstance.color = c;
+
+        DontDestroyOnLoad(gameObject);
```
Comment (otherotherjosh) [inline Assets/OurFiles/Scripts/SceneLoading/SceneLoader.cs]: DontDestroyOnLoad is already called in Start()

**Review by otherotherjosh — CHANGES_REQUESTED** [review]
You're on the right track, we're just not quite there yet. The object with the original fade to black material on it still has the original material assigned, so it doesn't fade when this code runs.

File: Assets/OurFiles/Scripts/SceneLoading/SceneLoader.cs (hunk 1 above)
Comment (MikeBike2) [reply Assets/OurFiles/Scripts/SceneLoading/SceneLoader.cs]: ah i see now thanks for pointing that out!

**Review by otherotherjosh — APPROVED** [review]
It has been fixed!!

**Review by Christian-Irvine — CHANGES_REQUESTED** [review]
Nice work, you have fixed the issue with the fading. In the `SceneLoadManager` the Cam Overlay hasn't been assigned but when you assign it, the code works perfectly. Once this is fixed up I'm happy to approve.

**Review by Christian-Irvine — APPROVED** [review]
After some consideration, I realized we will need to assign the Cam Overlay in the menu anyways so this can be fixed in the hotfix. Happy to approve.
