### PR TITLE
Pathfinding

### LINKED ISSUE #29: Pathfinding
**Description**
We want to have modular and dynamic crowds that can fill the scene and walk around using Unity's pathfinding system.

**Screenshots**

Image

### LINKED ISSUE #30: NPCs leaving Coherency
**Describe the bug**
Currently NPCs leaving coherency assumes they can only leave by walking out of the coherency zone. However NPCs can leave the zone in other ways than just walking out or the player walking away e.g. dying, despawning etc etc

This is bad becuase it will now leave a hanging counter for a NPC that is not there causing eventually the player to be in coherency when no NPCs are around.

**Expected behavior**
The coherency count should represent how many NPCs are coherent with the player.

### PR DESCRIPTION
**Pull request by Loerad**
## Describe your changes

I have created a full pathfinding system for our level

This system is controlled by various spawn points at each of the level edges that spawn NPCs randomly with a goal point that is not their spawn point.

You can toggle the spawning with a bool on the Spawn points game object at any time.

image

## Issue number and link

#28
#30

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Loerad** [comment]
Now a real pr

**Review by Christian-Irvine — APPROVED** [review]
Nice work, I love having npcs walking around it really gives the game a good feel it never had before. One thing I noticed was the console slowly filled up with warning messages: 
image
but it wasn't breaking so it is probably just something to look into. Otherwise the code looks good and they function as intended, Happy to approve!

**Comment by Loerad** [comment]
> Nice work, I love having npcs walking around it really gives the game a good feel it never had before. One thing I noticed was the console slowly filled up with warning messages: image but it wasn't breaking so it is probably just something to look into. Otherwise the code looks good and they function as intended, Happy to approve!

was there npc's walking around?

File: Assets/OurFiles/Scripts/NPC/CrowdManager.cs [hunk 1]
```diff
@@ -1,38 +1,91 @@
...
+        }
+    }
+
+    private List<GameObject> RemoveExcludedSpawnPoints(List<GameObject> includedSpawnPoints, List<int> excludedSpawnPoints)
+    {
+        List<GameObject> destroyedPoints = new();
+
+        for (int i = 0; i < includedSpawnPoints.Count; i++)
+        {
+            for (int j = 0; j < excludedSpawnPoints.Count; j++)
```
Comment (lolyay270) [inline Assets/OurFiles/Scripts/NPC/CrowdManager.cs:74]: This code works perfectly fine, 
but could be made more readable with [List.Contains](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.contains) or [List.Exists](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.contains)

File: Assets/OurFiles/Scripts/NPC/NPCPather.cs [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+        if (agent.hasPath) //waits for generation
+        {
+            distance = 0.0f;
+            Vector3[] corners = agent.path.corners;
+            for (int i = 0; i < corners.Length - 1; i++)
+            {
+                distance += Mathf.Abs((corners[i] - corners[i + 1]).magnitude);
+            }
+
+            if (agent.path.status == NavMeshPathStatus.PathComplete && distance <= 0.5f)
```
Comment (lolyay270) [inline Assets/OurFiles/Scripts/NPC/NPCPather.cs:26]: This 0.5 is a magic number

File: Assets/OurFiles/Scripts/NPC/NPCSpawner.cs [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+    private void SpawnNPC(Transform spawn, Transform goal)
+    {
+        GameObject activeNPC = Instantiate(npc, spawn.position + new Vector3(0, 0.75f, 0), Quaternion.identity);
+        activeNPC.GetComponent<NPCPather>().SetGoalAndHome(goal, spawn);
+    }
+
+    /// <summary>
+    /// Tuple <c>ReturnSpawnPoint</c> returns a random spawn point and its index.
+    /// </summary>
+    private (Transform, int) ReturnSpawnPoint() //this is a tuple but .NET 7 style or something weird. Understood how it works from here https://stackoverflow.com/questions/34798681/method-with-multiple-return-types
```
Comment (lolyay270) [inline Assets/OurFiles/Scripts/NPC/NPCSpawner.cs:55]: This returning of tuples is super cool
I hope to use it in the future

**Review by lolyay270 — APPROVED** [review]
Super awesome feature that really is starting to add life to our little scene
I have found some tiny tweaks that could help the code quality in future cases

Happy to approve since there are no bugs that i could find

Also in the future please try to add a parent to spawned objects in the scene so the hierarchy doesnt look like this
image

**Review by otherotherjosh — CHANGES_REQUESTED** [review]
I'm gonna be annoying and request that you change this as Jenna mentioned earlier;
> Also in the future please try to add a parent to spawned objects in the scene so the hierarchy doesnt look like this
> image

An empty object named "NPCs" would suffice.

I have playtested this branch and found that I can not teleport on the road, which could be highly problematic for people who don't use the walk movement.

Besides that, this is really exciting to see!! The scene feels so alive, which means a lot given that it's just a bunch of moving beans.

File: Assets/OurFiles/Scripts/NPC/CrowdManager.cs (hunk 1 above)
Comment (Loerad) [reply Assets/OurFiles/Scripts/NPC/CrowdManager.cs:74]: this is done

**Comment by Loerad** [comment]
I am personally of the opinion that adding a parent to those NPCs doesn't matter as it is only in runtime and will always be at the bottom of the hierarchy so will not be an issue unless that is something people really want.

**Comment by Loerad** [comment]
eh ill do it anyway

**Review by otherotherjosh — APPROVED** [review]
Thank you for making these changes!! Interestingly, we cannot teleport on the crossings that the NPCs use but I don't care about that right now, it's a lot better than not being able to move on the road at all.

File: Assets/OurFiles/Scripts/NPC/CrowdManager.cs [hunk 4]
```diff
@@ -1,38 +1,87 @@
...
+        }
+    }
+
+    private List<GameObject> RemoveExcludedSpawnPoints(List<GameObject> includedSpawnPoints, List<int> excludedSpawnPoints)
+    {
+        List<GameObject> destroyedPoints = new();
+
+        for (int i = 0; i < includedSpawnPoints.Count; i++)
+        {
+            if (excludedSpawnPoints.Contains(includedSpawnPoints.IndexOf(includedSpawnPoints[i])))
```
Comment (lolyay270) [inline Assets/OurFiles/Scripts/NPC/CrowdManager.cs:74]: This looks super good
just being nitpicky now, just wondering if there is a way to make the code even tidier
something like this maybe (note this code doesnt work at all), and if its not possible then np
```c#
 private List<GameObject> RemoveExcludedSpawnPoints(List<GameObject> includedSpawnPoints, List<int> excludedSpawnPoints)
    {
        for (int i = 0; i < excludedSpawnPoints.Count; i++)
        {
            if (includedSpawnPoints.Contains(excludedSpawnPoints[i]))
            {
                includedSpawnPoints.Remove(includedSpawnPoints[i]);
            }
        }
        return includedSpawnPoints;
    }
   ```

**Review by lolyay270 — APPROVED** [review]
All changes requested have been added
