### PR TITLE
Stop player walking through walls

### LINKED ISSUE #12: Player can move when paused
**Describe the bug**
When in pause menus or main menu, the player can use continuous or teleportation movement.

**To Reproduce**
1. load the game into main menu
2. move the left stick in any direction
3. move the right stick forward and aim at floor
4. click "play" and load game scene
5. move both sticks as stated above

**Expected behavior**
The player should not be able to move when in a paused state

**Additional context**
`UnityEngine.XR.Interaction.Toolkit.Samples.StarterAssets.ControllerInputActionManager.DisableAllLocomotionActions();` does seem to stop player movement

### LINKED ISSUE #13: Player can move thru walls
**Describe the bug**
player characters can be pushed thru the walls if the user moves irl

**To Reproduce**
1. launch game, click "play" and load the game scene
2. move the player character against any wall
3. move forwards in real life to push the camera thru the in game wall
4. move the player character in game

**Expected behavior**
movement irl should not allow the in game character to clip thru walls

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by otherotherjosh**
Closes #13

## Changes
- Added `XRPushbackProvider` 
  - It is a `LocomotionProvider` which uses `TryQueueTransformation()` to move the CharacterController on the player
  - It checks for collision by Raycasting from the camera position in 3 directions (left, right, forward) then calculating the direction the wall (if there is one) is facing
- Added Pushback object as child of the player, in the **PlayerMoveFix** scene _(I did not override the prefab)_

## Bugs, Problems and Quirks
- Sometimes the player gets pushed back because of the player collider and not the calculated pushback motion _(perhaps the constant calling of `TryQueueTransformation()` is updating the player body position to where the head is)_ and this is noticeably choppy

### CODE REVIEW

**Review by Christian-Irvine — APPROVED** [review]
Awesome work. I really like the way you integrated this in with the already existing system, it works well and was a much needed addition to our game. Happy to approve

File: Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs [hunk 1]
```diff
@@ -0,0 +1,86 @@
+using System.Collections.Generic;
+using UnityEngine;
+using UnityEngine.UIElements;
```
Comment (Loerad) [inline Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs:3]: Using directive is unnecessary. Remove this directive

File: Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+//   https://www.youtube.com/watch?v=FVPnp3fTGnw
+public class XRPushbackProvider : LocomotionProvider
+{
+    [SerializeField] private float detectionDistance = 0.2f;
+    [SerializeField] private LayerMask detectionLayers;
+    [SerializeField] private Transform playerCamera;
+    [SerializeField] private float pushbackStrength = 1;
+    private List<RaycastHit> detectedHits;
+
+    public XROriginMovement transformation { get; set; } = new XROriginMovement();
```
Comment (Loerad) [inline Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs:18]: Naming rule violation: Capitalize transformation because it is a public variable.

File: Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+
+    private CharacterController m_CharacterController;
+    private bool m_AttemptedGetCharacterController;
+
+    void Update()
+    {
+        if (mediator.xrOrigin?.Origin == null)
```
Comment (Loerad) [inline Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs:25]: Unity objects should not use null propagation. 

Fix with this: `mediator.xrOrigin != null ? mediator.xrOrigin.Origin : null == null`

File: Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+        {
+            return;
+        }
+
+        FindCharacterController();
+
+        detectedHits = DetectCollision(playerCamera, detectionDistance, detectionLayers);
+        Vector3 direction = CalculatePushbackDirection();
+        Vector3 motion = direction * pushbackStrength * Time.deltaTime;
```
Comment (Loerad) [inline Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs:34]: Re-order operands for better performance.

`Vector3 motion = pushbackStrength * Time.deltaTime * direction;`

File: Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs [hunk 5]
```diff
@@ -0,0 +1,86 @@
...
+    }
+
+    private void FindCharacterController()
+    {
+        GameObject gameObject = base.mediator.xrOrigin?.Origin;
+        if (!(gameObject == null) && m_CharacterController == null && !m_AttemptedGetCharacterController)
+        {
+            if (!gameObject.TryGetComponent<CharacterController>(out m_CharacterController) && gameObject != base.mediator.xrOrigin.gameObject)
+            {
+                base.mediator.xrOrigin.TryGetComponent<CharacterController>(out m_CharacterController);
```
Comment (Loerad) [inline Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs:51]: Anything with base. can be simplified to not have it

File: Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+        if (base.locomotionState == LocomotionState.Moving)
+        {
+            transformation.motion = motion;
+            TryQueueTransformation(transformation);
+        }
+    }
+
+    private void FindCharacterController()
+    {
+        GameObject gameObject = base.mediator.xrOrigin?.Origin;
```
Comment (Loerad) [inline Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs:46]: Unity objects should not use null propagation
 and Name can be simplified

`GameObject gameObject = mediator.xrOrigin != null ? mediator.xrOrigin.Origin : null;`

File: Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+        }
+    }
+
+    private List<RaycastHit> DetectCollision(Transform origin, float distance, LayerMask mask)
+    {
+        List<RaycastHit> newDetectedHits = new();
+
+        List<Vector3> directions = new() { origin.forward, origin.right, -origin.right };
+        
+        RaycastHit hit;
```
Comment (Loerad) [inline Assets/OurFiles/Scripts/Player/XRPushbackProvider.cs:64]: This can be put inline
 ```
        //RaycastHit hit; << remove this
        foreach (Vector3 direction in directions)
        {
            if (Physics.Raycast(origin.position, direction, out RaycastHit hit, distance, mask))

**Review by Loerad — APPROVED** [review]
Looks really good!

A few things that could be changed in the code for best practice.
